version: "3.9"
services:
  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    command: >
      --port 8080
      --api-key ${MCPO_API_KEY}
      -- npx n8n-mcp
    environment:
      MCP_MODE: stdio
      LOG_LEVEL: error
      DISABLE_CONSOLE_OUTPUT: "true"
      N8N_API_URL: ${N8N_API_URL}
      N8N_API_KEY: ${N8N_API_KEY}
    ports:
      - "8080:8080"
