version: '3.8'

services:
  n8n-mcp:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - N8N_URL=${N8N_URL}
      - N8N_API_KEY=${N8N_API_KEY}
    networks:
      - coolify
    restart: unless-stopped

  mcpo:
    image: ghcr.io/open-webui/mcpo:latest
    environment:
      - MCPO_API_KEY=${MCPO_API_KEY}
      - MCP_SERVERS=[{"id":"n8n","name":"n8n-mcp","command":"node","args":["npm","start"],"env":{"N8N_URL":"${N8N_URL}","N8N_API_KEY":"${N8N_API_KEY}"},"cwd":"/app","host":"n8n-mcp"}]
    depends_on:
      - n8n-mcp
    networks:
      - coolify
    expose:
      - "8080"
    restart: unless-stopped

networks:
  coolify:
    external: true
