version: "3.9"
services:
  n8n-mcp:                                  # gleicher Name, damit Coolify die Ressource 1:1 ersetzt
    image: ghcr.io/open-webui/mcpo:main
    command: >
      --port 8080
      --api-key ${MCPO_API_KEY}
      -- npx n8n-mcp
    environment:
      MCP_MODE: stdio
      LOG_LEVEL: error
      DISABLE_CONSOLE_OUTPUT: "true"
      N8N_API_URL: ${N8N_API_URL}
      N8N_API_KEY: ${N8N_API_KEY}
    labels:
      - traefik.enable=true
      # Router-Regel nur Host(), KEIN PathPrefix
      - traefik.http.routers.mcp.rule=Host(`mcp-n8n-doc.srai.ch`)
      # Richtiger Entrypoint-Name in Coolify v4
      - traefik.http.routers.mcp.entrypoints=https
      # TLS aktivieren (Coolify setzt automatisch den letsencrypt-Resolver)
      - traefik.http.routers.mcp.tls=true
      # Dienst-Port bleibt 8080 im Container
      - traefik.http.services.mcp.loadbalancer.server.port=8080
      # Unbedingt genau das Docker-Netz, in dem Traefik steckt
      - traefik.docker.network=coolify
    networks:
      - coolify
    restart: unless-stopped

networks:
  coolify:
    external: true
