version: '3.8'

services:
  n8n-mcp:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - N8N_URL=${N8N_URL}
      - N8N_API_KEY=${N8N_API_KEY}
    volumes:
      - ./dist:/app/dist
    networks:
      - coolify
    restart: unless-stopped

  mcpo:
    image: ghcr.io/open-webui/mcpo:latest
    environment:
      # MCPO API Key (erforderlich) [2]
      - MCPO_API_KEY=${MCPO_API_KEY}
      # MCP Server Konfiguration mit n8n Environment Variables
      - MCP_SERVERS=[{"id":"n8n","name":"n8n-mcp","command":"node","args":["/app/dist/index.js"],"env":{"N8N_URL":"${N8N_URL}","N8N_API_KEY":"${N8N_API_KEY}"},"cwd":"/app"}]
    volumes:
      - ./dist:/app/dist:ro
    depends_on:
      - n8n-mcp
    networks:
      - coolify
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=mcpo-n8n"
      - "coolify.domain=mcp-n8n-doc.srai.ch"
      - "coolify.port=8080"
      - "coolify.generateSSL=true"
    restart: unless-stopped

networks:
  coolify:
    external: true
